export { default as Navbar } from './Navbar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as About } from './About/About'
export { default as Skill } from './Skill/Skill'
export { default as ProjectList } from './ProjectList/ProjectList'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'
